### ISSUE TITLE
wanderlust does not save password

### ISSUE THREAD

**Issue by XANi** [wanderlust/wanderlust#106] opened 2015-09-08 17:17 UTC
Environment:
* emacs 24.5 (debian pkg) with empty config except adding melpa repos
* wanderlust from melpa, clean install
* config only have smtp/imap acct related setting

what happens:

if I start wanderlust, enter correct login I get connected, but variable `elmo-passwd-alist` is nil and so it is passwd file when saved

`(elmo-get-passwd "sth")` followed by `(elmo-passwd-alist-save)` saves the password correctly

if I then restart emacs, it does not load saved entries.

**Comment by egh** [comment] 2015-09-08 17:36
This should be expected behavior: you need to run `elmo-passwd-alist-save` to save your passwords.

**Comment by XANi** [comment] 2015-09-08 22:44
yes, `elmo-passwd-alist-save` works.

just that when I type password during login it doesn't get added to `elmo-passwd-alist` so saving only results in `nil` string saved into file....

and when I create and save password manually, then restart emacs and start wl, it does not get loaded anyway

**Comment by egh** [comment] 2015-09-08 23:01
Sorry, I didn't understand this issue.

Still, I can't reproduce this on emacs 24.5 (on ubuntu 15.04) + MELPA wanderlust + IMAP account. I started with `emacs -q` and just loaded my packages. WL would still have loaded `.wl` on startup though. Is it possible you have set `elmo-passwd-life-time` or something?

**Comment by ikazuhiro** [comment] 2015-09-09 13:29
Wanderlust has a bug that password for PLAIN authentication on IMAP4 protocol is never saved.  If you use it, please other authentication type (such as CLEAR) as workaround.

**Comment by XANi** [comment] 2015-09-09 14:37
Thanks for help @ikazuhiro, that fixed it.

I was following http://emacswiki.org/emacs/WanderLust , it has `plain` as auth type and I just followed instructions.

I guess the docs should be updated to use `clear` instead.

**Comment by ikazuhiro** [comment] 2015-09-09 22:10
I've committed [the fix] (https://github.com/wanderlust/wanderlust/commit/f2ab75e6a32a4e90ccbbe95cbcd85f74d8c4291b).  BTW, as far as I confirmed, the example of [EmacsWiki's page] (http://emacswiki.org/emacs/WanderLust) does not use `plain` authentication type for IMAP folder.

**Closed** 2015-09-13 23:47 UTC
